#!/bin/csh
########################################################################
# StarRC Reference Methodology Run Script                              #
# Gate Level Flow                                                      #
# Script: run_starrc                                                   #
# Version: K-2015.12 (January 11, 2016)                                #
# Copyright (C) 2010-2016 Synopsys, Inc. All rights reserved.          #
########################################################################

# Before running the script, set the variable $STAR_PATH to the latest StarXtract executable location
mkdir results reports
set path=($STAR_PATH $path)
StarXtract -clean ./rm_starrc_scripts/star_cmd_gate


